/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import konfigurasi.AmbilKRS;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import konfigurasi.Konfigurasi;


/**
 *
 * @author hadie
 */
public class AmbilKRSForm extends javax.swing.JFrame {

    String namaMHS,npmMHS;
    
   
    public AmbilKRSForm() {
        initComponents();

        


   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        labelNama1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelNPM1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAmbilKRS = new javax.swing.JTable();
        buttonSelesai = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboSemester = new javax.swing.JComboBox<>();
        comboGG = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel3.setText("NPM   :");

        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tableAmbilKRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "KODE MATAKULIAH", "MATA KULIAH", "SKS", "KELAS", "AMBIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAmbilKRS.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableAmbilKRSAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tableAmbilKRS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAmbilKRSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAmbilKRS);
        if (tableAmbilKRS.getColumnModel().getColumnCount() > 0) {
            tableAmbilKRS.getColumnModel().getColumn(0).setMinWidth(130);
            tableAmbilKRS.getColumnModel().getColumn(0).setPreferredWidth(130);
            tableAmbilKRS.getColumnModel().getColumn(0).setMaxWidth(130);
            tableAmbilKRS.getColumnModel().getColumn(1).setMinWidth(200);
            tableAmbilKRS.getColumnModel().getColumn(1).setMaxWidth(400);
            tableAmbilKRS.getColumnModel().getColumn(2).setMinWidth(0);
            tableAmbilKRS.getColumnModel().getColumn(2).setMaxWidth(100);
            tableAmbilKRS.getColumnModel().getColumn(3).setMinWidth(200);
            tableAmbilKRS.getColumnModel().getColumn(3).setMaxWidth(300);
            tableAmbilKRS.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(new JComboBox(new String[] {"5A reg Pagi Banjarbaru", "5B reg Pagi Banjarbaru", "5C reg Pagi Banjarbaru", "5M reg Pagi Banjarbaru" })));
            tableAmbilKRS.getColumnModel().getColumn(4).setMinWidth(50);
            tableAmbilKRS.getColumnModel().getColumn(4).setPreferredWidth(50);
            tableAmbilKRS.getColumnModel().getColumn(4).setMaxWidth(50);
        }

        buttonSelesai.setText("Selesai");
        buttonSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelesaiActionPerformed(evt);
            }
        });

        jLabel5.setText("SEMESTER");

        comboSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------" }));
        comboSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSemesterActionPerformed(evt);
            }
        });

        comboGG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "GANJIL", "GENAP" }));
        comboGG.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboGGAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        comboGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGGActionPerformed(evt);
            }
        });

        jLabel1.setText("NAMA :");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("KARTU RENCANA STUDI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNPM1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(135, 135, 135))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonSelesai)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(comboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNPM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(107, 107, 107)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSelesai)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboGGAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboGGAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGGAncestorAdded
void setLabel1(){
        labelNama1.setText(namaMHS);
        labelNPM1.setText(npmMHS);
}
    private void tableAmbilKRSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAmbilKRSMouseClicked

try{
       int row = tableAmbilKRS.getSelectedRow();

                Date now = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmss");
                String TGL = sdf.format(now);

        String kodeKRS = "KRS"+TGL;
        String npm = npmMHS;
        String kode = tableAmbilKRS.getValueAt(row, 0).toString();
        String makul = tableAmbilKRS.getValueAt(row, 1).toString();
        String sks = tableAmbilKRS.getValueAt(row, 2).toString();
        String kelas = tableAmbilKRS.getValueAt(row, 3).toString();
        String ambil = "DITERIMA";
        String centang = tableAmbilKRS.getValueAt(row, 4).toString();
        Boolean isCentang = Boolean.valueOf(centang);
        if(isCentang){
           String[] NK = {"kode_krs","npm","kode","nama_makul","sks","kelas","ambil"};
           String[] isinya ={kodeKRS,npm,kode,makul,sks,kelas,ambil};
           new Konfigurasi().Simpan("ambilkrs", NK, isinya);
        }
        }catch(Exception e){
              JOptionPane.showMessageDialog(null,"PILIH KELAS!");
    }

    }//GEN-LAST:event_tableAmbilKRSMouseClicked
 
    private void buttonSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelesaiActionPerformed

                dispose();
              MenuMHSForm mh = new MenuMHSForm();
              mh.nama = namaMHS;
              mh.npm = npmMHS;
              mh.setLabel();
              mh.setVisible(true);
    }//GEN-LAST:event_buttonSelesaiActionPerformed

    private void comboGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGGActionPerformed

        
        if(comboGG.getSelectedItem().equals("-PILIH-")){
            comboSemester.setVisible(false);
        }
        else if(comboGG.getSelectedItem().equals("GANJIL")){
             comboSemester.setVisible(true);
            comboSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] 
            { "Semester 1","Semester 3","Semester 5","Semester 7"}));
        }else{
             comboSemester.setVisible(true);
            comboSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] 
            { "Semester 2","Semester 4","Semester 6","Semester 8" }));
        }
    }//GEN-LAST:event_comboGGActionPerformed

    private void comboSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSemesterActionPerformed
       if(comboSemester.getSelectedItem().equals("Semester 1")){
  
        }else if(comboSemester.getSelectedItem().equals("Semester 2")){
            
        }else if(comboSemester.getSelectedItem().equals("Semester 3")){
             
        }else if(comboSemester.getSelectedItem().equals("Semester 4")){
         
        }else if(comboSemester.getSelectedItem().equals("Semester 5")){
           dispose();
           
                        try{

                    AmbilKRSForm krs = new AmbilKRSForm();
                    krs.namaMHS = labelNama1.getText();
                    krs.npmMHS = labelNPM1.getText();
                    krs.setLabel1();
                    krs.tampilanUI();
                    krs.pack();
                    krs.combo();
                    krs.setLocationRelativeTo(null);
                    krs.setVisible(true);
                

        } catch (SQLException ex) {
            Logger.getLogger(AmbilKRSForm.class.getName()).log(Level.SEVERE, null, ex);
        }   
        }else if(comboSemester.getSelectedItem().equals("Semester 6")){

        }else if(comboSemester.getSelectedItem().equals("Semester 7")){
            
        }else{
             

        }
    }//GEN-LAST:event_comboSemesterActionPerformed

    private void tableAmbilKRSAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableAmbilKRSAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAmbilKRSAncestorAdded

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
              MenuMHSForm mh = new MenuMHSForm();
              mh.nama = namaMHS;
              mh.npm = npmMHS;
              mh.setLabel();
              mh.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed
void combo(){
      comboSemester.setVisible(false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmbilKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmbilKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmbilKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmbilKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              // try {
                    AmbilKRSForm krs = new AmbilKRSForm();
                    krs.pack();
                    krs.setLocationRelativeTo(null);
                    krs.setVisible(true);
                    krs.combo();
                
//                } catch (SQLException ex) {
//                    Logger.getLogger(AmbilKRSForm.class.getName()).log(Level.SEVERE, null, ex);
//               }
                
            }
        });
    }

    void tampilanUI() throws SQLException{
    AmbilKRS ambilKrs;
    ArrayList<AmbilKRS> ambilKrsArrayList = new ArrayList<>();
    Konfigurasi myConnection = new Konfigurasi();
    Connection con = myConnection.getKoneksi();
    
    String selectQuery = "SELECT * FROM matakuliah";
     Statement statement;
     ResultSet resultSet;
    
    try{
        statement = con.createStatement();
        resultSet = statement.executeQuery(selectQuery);
        while (resultSet.next())
        {
            ambilKrs = new AmbilKRS(
                    resultSet.getString("kode"),
                    resultSet.getString("nama_makul"),
                    resultSet.getInt("sks")
     
            );
                        ambilKrsArrayList.add(ambilKrs);
              }
          }catch (SQLException e)
          {
              e.printStackTrace();
    }


     DefaultTableModel dtm = (DefaultTableModel) tableAmbilKRS.getModel();
        dtm.setRowCount(0);
        Object [] row = new Object[3];
       int i = 1;
       for (AmbilKRS value : ambilKrsArrayList){
        
        row [0] = value.getKode();
        row [1] = value.getNamaMakul();
        row [2] = value.getSKS();

        

          dtm.addRow(row);
            i++;
            
           
      }
    }

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton buttonSelesai;
    private javax.swing.JComboBox<String> comboGG;
    private javax.swing.JComboBox<String> comboSemester;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNPM1;
    private javax.swing.JLabel labelNama1;
    private javax.swing.JTable tableAmbilKRS;
    // End of variables declaration//GEN-END:variables



}

